export enum commands {
  PROFILE_WRITE = 'akord:profile:write',
  VAULT_WRITE = 'akord:dataroom:write',
  VAULT_ARCHIVE = 'akord:dataroom:archive',
  VAULT_RESTORE = 'akord:dataroom:restore',
  VAULT_DELETE = 'akord:dataroom:delete',
  MEMBERSHIP_WRITE = 'akord:membership:write',
  MEMBERSHIP_OWNER = 'akord:membership:owner',
  MEMBERSHIP_INVITE = 'akord:membership:invite',
  MEMBERSHIP_INVITE_NEW_USER =
  'akord:membership:invite-new-user',
  MEMBERSHIP_CONFIRM = 'akord:membership:confirm',
  MEMBERSHIP_ACCEPT = 'akord:membership:accept',
  MEMBERSHIP_REJECT = 'akord:membership:reject',
  MEMBERSHIP_REVOKE = 'akord:membership:revoke',
  STACK_WRITE = 'akord:stack:write',
  STACK_REVOKE = 'akord:stack:revoke',
  STACK_RESTORE = 'akord:stack:restore',
  STACK_DELETE = 'akord:stack:delete',
  MEMO_WRITE = 'akord:memo:write',
  MEMO_ADD_REACTION = 'akord:memo:add-reaction',
  MEMO_REMOVE_REACTION = 'akord:memo:remove-reaction',
  FOLDER_WRITE = 'akord:folder:write',
  FOLDER_REVOKE = 'akord:folder:revoke',
  FOLDER_RESTORE = 'akord:folder:restore',
  FOLDER_DELETE = 'akord:folder:delete',
  NOTE_WRITE = 'akord:note:write',
  NOTE_REVOKE = 'akord:note:revoke',
  NOTE_RESTORE = 'akord:note:restore',
};