export enum reactionEmoji {
  JOY = "128514",
  ASTONISHED = "128562",
  CRY = "128557",
  HEART = "10084,65039",
  FIRE = "128293",
  THUMBS_UP = "128077",
  THUMBS_DOWN = "128078",
  PRAY = "128591"
};

export enum objectTypes {
  VAULT = "Vault",
  MEMBERSHIP = "Membership",
  STACK = "Stack",
  MEMO = "Memo",
  FOLDER = "Folder",
  NOTE = "Note"
};

export enum status {
  PENDING = "PENDING",
  INVITED = "INVITED",
  ACCEPTED = "ACCEPTED",
  REJECTED = "REJECTED",
  REVOKED = "REVOKED",
  ACTIVE = "ACTIVE",
  ARCHIVED = "ARCHIVED",
  DELETED = "DELETED"
};

export enum role {
  OWNER = "OWNER",
  CONTRIBUTOR = "CONTRIBUTOR",
  VIEWER = "VIEWER"
};

export enum actionRefs {
  VAULT_CREATE = "DATAROOM_CREATE",
  VAULT_RENAME = "DATAROOM_RENAME",
  VAULT_ARCHIVE = "DATAROOM_ARCHIVE",
  VAULT_RESTORE = "DATAROOM_RESTORE",
  VAULT_DELETE = "DATAROOM_DELETE",
  VAULT_KEY_ROTATE = "DATAROOM_KEY_ROTATE",
  MEMBERSHIP_INVITE = "MEMBERSHIP_INVITE",
  MEMBERSHIP_INVITE_RESEND = 'MEMBERSHIP_INVITE_RESEND',
  MEMBERSHIP_ACCEPT = "MEMBERSHIP_ACCEPT",
  MEMBERSHIP_REVOKE = "MEMBERSHIP_REVOKE",
  MEMBERSHIP_REJECT = "MEMBERSHIP_REJECT",
  MEMBERSHIP_LEAVE = "MEMBERSHIP_LEAVE",
  MEMBERSHIP_KEY_ROTATE = "MEMBERSHIP_KEY_ROTATE",
  MEMBERSHIP_CHANGE_ROLE = "MEMBERSHIP_CHANGE_ACCESS",
  MEMBERSHIP_PROFILE_UPDATE = "MEMBERSHIP_PROFILE_UPDATE",
  MEMBERSHIP_OWNER = "MEMBERSHIP_OWNER",
  MEMBERSHIP_CONFIRM = "MEMBERSHIP_CONFIRM",
  MEMO_CREATE = "MEMO_WRITE",
  MEMO_ADD_REACTION = "MEMO_ADD_REACTION",
  MEMO_REMOVE_REACTION = "MEMO_REMOVE_REACTION",
  FOLDER_CREATE = "FOLDER_CREATE",
  FOLDER_RENAME = "FOLDER_RENAME",
  FOLDER_MOVE = "FOLDER_MOVE",
  FOLDER_REVOKE = "FOLDER_REVOKE",
  FOLDER_RESTORE = "FOLDER_RESTORE",
  FOLDER_DELETE = "FOLDER_DELETE",
  STACK_CREATE = "STACK_CREATE",
  STACK_UPLOAD_REVISION = "STACK_UPLOAD_REVISION",
  STACK_RENAME = "STACK_RENAME",
  STACK_MOVE = "STACK_MOVE",
  STACK_REVOKE = "STACK_REVOKE",
  STACK_RESTORE = "STACK_RESTORE",
  STACK_DELETE = "STACK_DELETE",
  NOTE_CREATE = "NOTE_CREATE",
  NOTE_UPLOAD_REVISION = "NOTE_UPLOAD_REVISION",
  NOTE_RENAME = "NOTE_RENAME",
  NOTE_MOVE = "NOTE_MOVE",
  NOTE_REVOKE = "NOTE_REVOKE",
  NOTE_RESTORE = "NOTE_RESTORE",
  NOTE_DELETE = "NOTE_DELETE",
  PROFILE_UPDATE = "PROFILE_UPDATE"
};