name: Test akord-js methods

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies and build 🔧
        run: yarn install && yarn build
      - name: Run tests ⚙️
        env:
          ENV: "dev"
          EMAIL: ${{ secrets.AKORD_TEST_USER_EMAIL }}
          PASSWORD: ${{ secrets.AKORD_TEST_USER_PASSWORD }}
          EMAIL_2: ${{ secrets.AKORD_TEST_USER_2_EMAIL }}
          PASSWORD_2: ${{ secrets.AKORD_TEST_USER_PASSWORD }}
          EMAIL_3: ${{ secrets.AKORD_TEST_USER_3_EMAIL }}
          PASSWORD_3: ${{ secrets.AKORD_TEST_USER_PASSWORD }}
        run: yarn test
